### ISSUE TITLE
Home app links not detecting metadata

### ISSUE THREAD

**Issue by Soleone** [GetScatter/ScatterDesktop#136]
I was wondering why in my Home screen in Scatter the EOSToolkit app was clickable whereas Chintai was not. I was just about to suggest to Chintai and NewDex to submit a PR to the `apps.json` file when I noticed they are already in there.

But for some reason only EOSToolkit gets detected here.

I assume it is related to the [applink](
https://github.com/GetScatter/ScatterApps/blob/a15b830d59015d7d187f8724dcabd150315b92fd/apps.json#L27).

![image](https://user-images.githubusercontent.com/2923/47059037-9a11f300-d195-11e8-94fc-aa16a81e8d10.png)

### Suggestion

1. Maybe these existing applinks needs to be fixed and instructions updated to ensure contributors realize that the app links need to match the url?

2. Or should something in Scatter Desktop be updated in [how the json data is looked](https://github.com/GetScatter/ScatterDesktop/blob/d165a38ad337f451fc8efe9f70b9537bf5301ea2/src/views/Home.vue#L160) up from the url/applink?

**Comment by nsjames** [comment]
Yeah it looks like their applinks are wrong ( should be the origin/domain for web apps ).
I just issued a fix for stripping the `www.` and sat there for 5 minutes pondering whether to just use the plugin name they specified. I think we should go with that to make usage consistent across all apps. 

All apps would have to update though in order to preserve their metas.

**Comment by nsjames** [comment]
I went ahead and changed chintai's applink manaully for now.

**Comment by nsjames** [comment]
I added a fix to the scatterjs-core lib to also strip `www.` from the origin so that should take care of the other issues.
