### ISSUE TITLE
 Scatter 10 Beta Feedback Summary

### ISSUE THREAD

**Issue by Soleone** [GetScatter/ScatterDesktop#220]
# Scatter 10 Beta Feedback

### 1️⃣  Explain what password is used for

On first welcome screen explain what the password is used for in one sentence, why do I care about this particular password? 

![image](https://user-images.githubusercontent.com/2923/49549360-81c97500-f8b6-11e8-8be0-22efbff8fc3b.png)
_Explanation could potentially replace the copy in the subtitle on this page_

### 2️⃣ Kill password alternative phrase

I have been seriously wondering if it is worth this extra complexity and breaking the normal use case of mnemonic seed words. Even with this clear warning I could see it confusing users and having unrealistic expectations (random example: users might be confused that using the same password results in completely different mnemonic words).

Having to take care of TWO secrets instead of one just seems more on the side of extra hassle than extra security in this case personally. Why not just cut it, what is the worse case scenario versus best case scenario?

![image](https://user-images.githubusercontent.com/2923/49546165-9c4b2080-f8ad-11e8-8085-3d7a0740bd4e.png)
_Scatter mnemonics just weird me out a little bit I guess_

### 3️⃣ Balance caret button

My instinct when seeing this button sitting there in prime real estate was that it brings me to my list of tokens that make up my balance. But instead I land in blockchain settings. I would argue that the use case of changing your blockchain filters is not common enough to warrant such a high profile button a the top of the home screen.

![image](https://user-images.githubusercontent.com/2923/49548378-88a2b880-f8b3-11e8-89d1-04991ceafd40.png)
_I see 54.75, I want to see how you got to that number that is why I click that button_

### 4️⃣  Where can I see the list of all keypairs I am managing with Scatter?

(Use case: Before destroying Scatter I wanted to ensure I have exported all my private keys.)

### 5️⃣ In settings consistently use toggle buttons for boolean settings

![image](https://user-images.githubusercontent.com/2923/49548585-2dbd9100-f8b4-11e8-9075-f60f88b42a74.png)
_Good_

![image](https://user-images.githubusercontent.com/2923/49548621-50e84080-f8b4-11e8-8e5f-72fb70eb8d50.png)
_Confusing: is it already disabled or will the click disable it?_

![image](https://user-images.githubusercontent.com/2923/49548663-74ab8680-f8b4-11e8-87ac-688462a4b448.png)
_Confusing: am I currently showing all or will the click do it?_

### 6️⃣ Minor copy adjustment

> Well what are you waiting for?

I like this small adjustment better: Well what are **we** waiting for?

Feels a bit more inviting, fits with piggy illustration to guide you through the experience.

![image](https://user-images.githubusercontent.com/2923/49546739-f4365700-f8ae-11e8-89ef-219d20687266.png)

### 7️⃣ Wallet terminology

> Wallet Name

After click Add keys I was first introduced to the term "wallet" within Scatter when it asked me to name the private key I just imported:

![image](https://user-images.githubusercontent.com/2923/49547831-d6b6bc80-f8b1-11e8-80a7-740f601747e3.png)

A normal user thinks Scatter is a wallet. And that they are importing a keypair and maybe naming that key pair. But in Scatter we are now managing multiple "wallets" and each keypair is connected to one wallet?

![image](https://user-images.githubusercontent.com/2923/49547985-488f0600-f8b2-11e8-8a45-f085e5bf1469.png)

Not 100% sure I quite follow why the term wallet is used for referring to keypairs, maybe that can be explained in one sentence somewhere.

**Comment by nsjames** [comment]
Awesome stuff. 
Most of this is now added for next testing build.

Things that weren't added:

**Removal of mnemonic** - We've been really mauling this one over lately as we agree it can be confusing. We have some additions coming to Scatter which will possibly make it irrelevant, but the point still stands that currently if a user ever loses their password and has keys they have yet to export those keys are completely lost. Scatter is likely going to become a full HD wallet in one of the next releases and that phrase will persist past password changes and be used to generate keys. We're just not there yet.

**Balance Caret** - Yes it might definitely make more sense to go to a global tokens panel when clicking on the caret with the ability to see a breakdown of **all** tokens in the wallet instead of being shot over to the token settings panel. In a future release we might remove the tokens panel from Settings and create a full-page tokens dashboard with all of the user's tokens on display as well as various settings.

**Comment by nsjames** [comment]
Closing. Scatter will be transferring to an HD wallet structure soon and a real "tokens panel" will be included. We have internal tickets for both of these items and this ticket is now redundant.
