### ISSUE TITLE
Feature Request: Transaction history

### ISSUE THREAD

**Issue by Soleone** [GetScatter/ScatterDesktop#243]
Warning: Probably a whole lot of work, but it might be one of those things that make the app feel more complete and well rounded, empowering the user and putting them in control:

## Anecdote

I just opened Scatter, and shortly after got a Telegram notification from eosauthority bot:

> Voting Event
> Voted to

For a second I was confused. then I remembered that I enabled auto-proxy vote in Scatter. But I wasn't sure which account just voted, and I thought that my accounts just a few days ago voted with Scatter already.

So now I have to check each of my accounts' transaction histories to see what exactly just happened.

## Suggestion

It would be nice to have a tab in Scatter that has the complete history of any blockchain transaction made with Scatter (potentially as an optional feature even). It could be a (list of?) json files, paginated in the app to not have to load too much data for users with hundreds of thousands of transactions.

Optionally which seems like more work and more network requests would be to sync with the blockchain and download all transactions for each account, and then filtering the ones made with this Scatter vs another client. But at this point it would be acting like a light block explorer, potentially a bit too much. But to be fair, every user should check their transaction history regularly, it seems like a 80% use case of EOS/blockchain.

As long as Scatter could locally store a log of each transaction made with this particular Scatter client in its own format and maybe just linking the transaction id to a block explorer, then that would already be quite good to get an audit of what my Scatter client did.

**Comment by nsjames** [comment]
Okay, so I added all the internal actions into the new history panel. It won't be caching anything that goes through the signing popups ( since there are no transaction ids on them yet due to them only being signed and not sent ) but it will cache all the various internal actions such as delegatebw, buyram, and proxy ( even invisible proxy revote ). <3

![image](https://user-images.githubusercontent.com/10360675/50592746-11564980-0e9e-11e9-9de1-3161c92bb883.png)
