### ISSUE TITLE
freezing

### ISSUE THREAD

**Issue by 3rdScout** [GetScatter/ScatterDesktop#259]
first Scatter froze while attempting to access network button to change to Telos. 
Then my password was useless after rebooting; got locked out. 
Attempted JSON recovery; locked again. 
Attempted upgrade to version 10.
Completely locks my whole system when launched. 
Unable to remove Scatter with "remove" software updater. 
Computer works well otherwise.
Help.

**Comment by nsjames** [comment]
It sounds like something about that data file is corrupted or otherwise malformed. 
I would just reset scatter completely and import your private keys into a new instance.

You can reset scatter and destroy all it's data by pressing "d" ten times on the login screen and then pressing the button that appears on the bottom of the screen. 

Let me know if that helps the problem or not

**Comment by 3rdScout** [comment]
It took a few times, but some form of resetting using pressing "d" ten times, then re installing, then importing old account with json file finally solved the problem. Thank you for your help.

**Comment by 3rdScout** [comment]
And avoiding new version 10, reverting back to version that crashed.

**Comment by nsjames** [comment]
Cleaning tickets for Scatter 11 testing release (makes this ticket no longer relevant)
