### ISSUE TITLE
User reports not being able to copy and paste private key

### ISSUE THREAD

**Issue by ramijames** [GetScatter/ScatterDesktop#280]
This is what they encounter:

<img width="1483" alt="screen shot 2019-01-21 at 4 44 56 pm" src="https://user-images.githubusercontent.com/814302/51481246-140cd600-1d9c-11e9-9788-9b554b600d63.png">

Nothing gets copied to the clipboard.

**Comment by nsjames** [comment]
This is likely a data corruption issue. When they click copy or reveal it can't decrypt the private key using the seed because the encrypted data doesn't match the decryption key anymore. 

I've got a ticket about setting up a hammer-test for the change password ( which seems to be what causes this in most cases ) in trello which i'm hoping can find the reason for this.

For that user specifically they will have to try to import a recent backup which doesn't have that corruption.

**Comment by nsjames** [comment]
Cleaning tickets for Scatter 11 testing release (makes this ticket no longer relevant)
