### ISSUE TITLE
EOS main net disappeared from my networks

### ISSUE THREAD

**Issue by ramijames** [GetScatter/ScatterDesktop#286]
Went to send you TRX and noticed that it was writing "jungle" above my EOS account. I had added it last week while testing. I went into networks and mainnet is just gone for me now. Can't see EOS mainnet in the known networks list.

<img width="925" alt="screen shot 2019-01-22 at 10 24 08 am" src="https://user-images.githubusercontent.com/814302/51521645-e2dde580-1e2f-11e9-8969-4474823efd2b.png">
<img width="927" alt="screen shot 2019-01-22 at 10 23 58 am" src="https://user-images.githubusercontent.com/814302/51521646-e2dde580-1e2f-11e9-8bb5-4e9402d91fff.png">
<img width="926" alt="screen shot 2019-01-22 at 10 22 14 am" src="https://user-images.githubusercontent.com/814302/51521647-e2dde580-1e2f-11e9-95cb-075a75b5dab5.png">

**Comment by nsjames** [comment]
So, though it says jungle and points to a jungle node the chainID is actually the mainnet chainID. 
Did you add jungle by editing the existing network or clicking the "Add" button first and creating a new network?

In my local I already made that "Add" button blue to make it more defined, but I'll also add a ticket to add a "New" translation and change that button to say "New" instead of "Add" since I think it's a little confusing.

![image](https://user-images.githubusercontent.com/10360675/51528481-72d75b80-1e3f-11e9-8148-d67803fb9c43.png)

**Comment by nsjames** [comment]
Alrighty, so closing this for now since it duplicates an internal ticket.
