### ISSUE TITLE
adding new networks, linking user

### ISSUE THREAD

**Issue by robertkowalski** [GetScatter/ScatterDesktop#318]
Hi James,

thanks for Scatter! People use it a lot with eosfinex. Right now we want to further improve the Scatter integration in eosfinex, to make it a really good user experience.

Right now eosfinex uses a sidechain setup, until confirmation times for transactions on main net become better.

We have a mainchain gateway that interacts with the sidechain, to create user accounts. The user needs accounts an both chains. 

When people try to login the first time on the sidechain, they get this popup:

![image](https://user-images.githubusercontent.com/298166/55325509-980ec880-5485-11e9-9bd5-b3b4d0f144fc.png)

The next step is to link the existing mainnnet account manually to the newly added network. Many people get confused by the shown error popup, so we had to write a tutorial: https://medium.com/eosfinexproject/tutorial-logging-in-using-scatter-b7058d88ad52

It would be cool if we could improve the addition of new networks, so that no tutorial or manual is needed.

We could maybe add an API call: `.linkUser` which opens a popup which asks "New network detected, do you want to link your user?" in case the network is not linked yet. 

What do you think?

**Comment by nsjames** [comment]
So actually, all of that is already supported. 
The general flow for that process on a testnet with no account for the user is as follows:

```
await ScatterJS.suggestNetwork(network);
if(!await ScatterJS.hasAccountFor(network)){
    const publicKey = await ScatterJS.getPublicKey('eos').catch(() => null);
    if(!publicKey) return console.error('No public key provided');
    const account = await BackEndAPI.createAccount(publicKey); {name:..., authority:'active', publicKey}
    ScatterJS.linkAccount(account, network);
}
ScatterJS.login({accounts:[network]});
```

That will go through the whole flow of adding a newly created account using some backend service.

**However**, if accounts already exist on the network that user has public keys imported for (such as snapshots from the mainnet on testnets) then it's even easier. 
```
await ScatterJS.suggestNetwork(network);
await ScatterJS.login({accounts:[network]});
```

The above will add the network to the user's Scatter **only** if it doesn't exist (will be under the domain name + some random appended uuid. For instance "paper.eosfinex.comiQld") or just return true if it exists, it will also use that network internally to search for all accounts with the public keys that the user has imported the first time it adds the network as long as the node being suggested has a `history` plugin enabled capable of returning `get_key_accounts` results.

A general suggestion we always offer is to have the suggested node/network data be some form of load balancer that you can switch out the actual underlying node or forward the domain. Otherwise the users will be stuck with that node in their Scatter with that specific chainId and it will always return `true` when trying to suggest the network without actually changing the node data.

**Comment by robertkowalski** [comment]
thx so much @nsjames!
