### ISSUE TITLE
Edge case: If scatter application is refreshed with 'CTRL + R' while developer console is open, the correct password will not unlock the wallet. Must close and re-open Scatter Desktop to successfully unlock again

### ISSUE THREAD

**Issue by acoutts** [GetScatter/ScatterDesktop#322]
Scatter Desktop v10.1.2

Steps to reproduce:
- Unlock Scatter Desktop
- Open developer console with F12
- Refresh with `CTRL + R`
- The unlock screen is shown again. Enter your password and it will say password is incorrect.
- Close / re-open Scatter Desktop and it will unlock with the same password as expected.

**Comment by nsjames** [comment]
This is by design.
The seed that is used for encryption/decryption exists only on the main process and the connection between the main and renderer process is secured with a single-session keypair. So when you refresh the page the renderer is refreshed and gets a new keypair, but the main process is not refreshed and still holds a reference to the old keypair from the renderer making it so you can't apply a new seed or use the old one.

You can see here there's even special logic for when running in development mode to bypass that since it's a hassle for development: https://github.com/GetScatter/ScatterDesktop/blob/master/electron.js#L262
