### ISSUE TITLE
SVG images need to be swapped out for PNGs

### ISSUE THREAD

**Issue by ramijames** [GetScatter/ScatterDesktop#328]
I'm attaching hover states for these, too.

![Screen Shot 2019-05-13 at 12 35 32 PM](https://user-images.githubusercontent.com/814302/57611496-ac151200-757b-11e9-9e16-1f9535a52a94.png)

[Archive 2.zip](https://github.com/GetScatter/ScatterDesktop/files/3172189/Archive.2.zip)

**Comment by nsjames** [comment]
I think we should stick to SVGs since this isn't the only place they are pulled in and the sizes will vary.

![image](https://user-images.githubusercontent.com/10360675/57645277-96790a00-75c6-11e9-9ee2-e5bd8eb7bbdd.png)

However, I think the other icons for these were cleaner and would solve the SVG issues
![image](https://user-images.githubusercontent.com/10360675/57645390-d7711e80-75c6-11e9-9e22-caa7ef5660b9.png)

**Comment by nsjames** [comment]
On that note I think this assets icon is cleaner as well.

![image](https://user-images.githubusercontent.com/10360675/57645461-fa9bce00-75c6-11e9-8095-34522c8e0976.png)

**Comment by nsjames** [comment]
7b9f890e0fbd18be391b2a890288c5944d1e5466

**Comment by nsjames** [comment]
We ended up sticking with the original icons for the `quick-actions` bar as the ones I suggested here did not look good as a replacement.
