### ISSUE TITLE
Error when signing arbitrary message with Ledger

### ISSUE THREAD

**Issue by RavenXce** [GetScatter/ScatterDesktop#372]
When using ScatterJS on version 10.1.2, 10.2.0, 11 of Scatter Desktop, signing arbitrary message from a web dApp does not work. This happens even before the "please connect wallet" screen appears.

This is the stack trace from the developer console (from compiled version atm, sorry).

```
Uncaught (in promise) TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at vendor.72d155327eb3de90c899.js:72
    at c (vendor.72d155327eb3de90c899.js:72)
    at new u (vendor.72d155327eb3de90c899.js:72)
    at a.value (app.bab9a9481e346778c8c7.js:1)
    at a.<anonymous> (app.bab9a9481e346778c8c7.js:1)
    at _ (vendor.72d155327eb3de90c899.js:136)
    at Generator._invoke (vendor.72d155327eb3de90c899.js:136)
    at Generator.t.(anonymous function) [as next] (file:///Applications/scatter.app/Contents/Resources/app.asar/dist/static/js/vendor.72d155327eb3de90c899.js:136:461269)
    at n (vendor.72d155327eb3de90c899.js:314)
    at vendor.72d155327eb3de90c899.js:314
```

**Comment by RavenXce** [comment]
By the way, the message appears fine. But nothing visually happens + this error appears in the console upon accepting the message.

**Comment by nsjames** [comment]
Can you show me the code you are trying to run to sign an arbitrary?

**Comment by RavenXce** [comment]
```js
const message = `Issue me a 30min Switcheo API key [${new Date().toUTCString()}]`
ScatterJS.scatter.getArbitrarySignature(`publicKey`, `message`)
```

The message appears fine, nothing happens when clicking the accept button.

**Comment by nsjames** [comment]
So, there's an issue with signing personal messages / arbitrary signatures with hardware devices. 
Because the ledger app doesn't (afaik) support signing arbitrary, we can't either. 

An example of using an on-chain contract for offline signing which works with hardware is here: https://github.com/GetScatter/scatter-js/blob/master/mock-sites/eosjs/index.html#L241

**Comment by mauhcs** [comment]
@nsjames this would work if the action called was ```transfer``` from ```eosio.token``` and put the arbitrary data in the ```memo``` field, no?
Sure, the signature is not for the data alone, but could have the same effect depending on the setup.

**Comment by nsjames** [comment]
That's correct, but a transfer isn't good as purely an authentication method since the users don't know that transaction isn't going to be signed and sent to the blockchain; they would just think they are transferring funds.

If however you're asking if signing a live transaction of any contract on the blockchain is a good method of proving key ownership, then yes of course. You should still check that the signature matches the key so you don't have to wait for asserts from the blockchain to verify.
