### ISSUE TITLE
Users don't know how to choose a strong password

### ISSUE THREAD

**Issue by Soleone** [GetScatter/ScatterDesktop#401]
A user reported today that it was too hard to create a new Scatter account because no matter which password they tried it wasn't accepted.

The error message simply stated: 

> Password not strong enough.

Looking at the [code](https://github.com/GetScatter/ScatterDesktop/blob/831190fc2d4ba39f0112333f0d17ae5b7c758ee7/src/services/secure/PasswordService.js#L21-L30) I wasn't sure how to interpret it immediately.

Edit: Looks like general rule of thumb right now is:

* longer password = higher score
* the more special characters (especially more than 5) you include of the following list the more secure it will be rated: `!@#$%^&*()_+-=[]{};':"\|,.<>/?`

Telegram link of user report: https://t.me/Scatter/93545

## Suggestion

1. More actionable error message.
2. Maybe ease the requirements, and just suggest a strong password, e.g. with status message as you type (weak, okay, strong, perfect), but don't enforce it.

**Comment by nsjames** [comment]
Yup, I've been discussing it with a lot of users by now and indeed the requirements right now are too high.
We had someone give up trying to find a strong password, not great :)

We're enforcing strong passwords for upcoming functionality (like cloud backups and device syncs for instance), and since we can't check the password strength after-the-fact it's important that it always starts strong.

**Comment by nsjames** [comment]
c7ae3f53638fca9a770a651103d5f6c143c9e698 lowered requirements
