### ISSUE TITLE
Scatter 11, login on nodes without history API

### ISSUE THREAD

**Issue by robertkowalski** [GetScatter/ScatterDesktop#410]
Hi Nathan,

hope you are well.

We have disabled the history api in our eos node because of the problems it can create.

It seems with Scatter 11 login does not work any more, except with manual configuration.

That makes it quite hard for us to onboard new users, is there a way to work around this issue? 

For example, we could setup a hyperion history node, do you have experience with integrating that for Scatter 11?

**Comment by nsjames** [comment]
The only route that is required for Scatter's use is the `get_key_accounts`. Since that currently resides in the history plugins you must run at least one type of them (state, light, or hyperion). 

I haven't checked what is required to use hyperion within Scatter, you might just have to match the route names (I think hyperion uses `/v2/`). 

Alternatively there are a few work arounds.
- For developers you can click the "..." menu on a keypair, hold down CTRL and then select the now exposed "Link Account" option which doesn't require a history node.
- For applications, you can use the `ScatterJS.linkAccount()` method to manually link an account for users, but this has limitations and you'll still need a history node to check what account belongs to what key. 

In reality, by far the easiest solution is to add a history plugin. You can tweak the plugin to ditch all information except for account<>key links, but I haven't seen a working concept of that yet.

Note: **We also require any network defined in our networks tab to have a history node running for their linked endpoint, or we remove them**.

**Comment by robertkowalski** [comment]
thx @nsjames!

**Comment by robertkowalski** [comment]
for easy reference, was added in https://github.com/eosrio/Hyperion-History-API/commit/a04fdc8de4e5df023dbb454a615facf5d4131e3b :)
