### ISSUE TITLE
Allow invalid HTTPS certifcates from whitelisted domains

### ISSUE THREAD

**Issue by liamcurry** [GetScatter/ScatterDesktop#47]
I'm trying to test using a local HTTPS node with a self-signed certificate but Scatter Desktop currently doesn't allow this. You get errors like this when you try:

![image](https://user-images.githubusercontent.com/77758/44960115-615cd980-aec7-11e8-864e-c8c200fba0ed.png)

It would be nice if Scatter Desktop had an option to accept invalid certificates, perhaps automatically from any manually added networks?

Accepting invalid certificates can be done with Electron's `certificate-error` event. Here are the docs with an example: https://electronjs.org/docs/api/app#event-certificate-error

**Comment by nsjames** [comment]
Hmm, since this is outside of the context of the remote I don't think it can be handled dynamically actually. The electron.js happens before it even knows about an user-added networks. I see no security issues with allowing 127.0.0.1 access to self-signed certs on local nodes, but localhost loopback could be a problem ( hosts file spoofing to external sources ).

**Comment by nsjames** [comment]
538315de25c3b72d8dbe928847480597b42a18da
