### ISSUE TITLE
FIO: Scatter showing address attached to local ETH wallet when it is not linked

### ISSUE THREAD

**Issue by ericbutz** [GetScatter/ScatterDesktop#509]
Use case:
* Create a FIO Address and map it to ETH (or another currency) in a different wallet (like Edge).
* In Scatter, import your FIO keys that are attached to the FIO Address.
* Open Scatter and it says that your FIO Address is mapped to the local Scatter ETH wallet. 
* The desired behavior is to validate the mapped ETH address and not allow the user to map it locally since you can currently only have one mapping per token code for a FIO pub key.

From Luke: Scatter is saying my luke@edge is attached to ETH Mainnet, but that is not the case. It's attached to multiple accounts within the Edge wallet, including ETH. It's a different key. I've verified this with the tool Anchor put togther: https://greymass.github.io/fio-register/ which pulls on-chain data.

**Comment by nsjames** [comment]
Is isn't necessarily saying it's linked to the **local** ETH address, just **an** ETH address.

![image](https://user-images.githubusercontent.com/10360675/84746555-cf9c5e80-afbe-11ea-9310-914e87afc0ea.png)
It would be the same with the rest of the system tokens on any network in this list. BTC for example would also show "Detach" because it already has an associated address. 

> The desired behavior is to validate the mapped ETH address** and not allow the user to map it locally** since you can currently only have one mapping per token code for a FIO pub key.

Since we can detach (assign to `0`) and re-attach another address, it should allow the user to do so within the wallet, no?
