### ISSUE TITLE
Problem with multiple networks 

### ISSUE THREAD

**Issue by nsjames** [GetScatter/ScatterDesktop#80]
```
Joe, [26.09.18 15:16]
any thoughts on the testnet thing that I mentioned Nathan?

Joe, [26.09.18 15:16]
@Randomnobody

Joe, [26.09.18 15:16]
[Forwarded from Joe]
it would appear that whichever network is last added "wins" with scatter at the moment and that network becomes scatter's default network context

nsjames | Scatter, [26.09.18 15:31]
[In reply to Joe]
Default network for what panels?

Joe, [26.09.18 15:36]
[In reply to nsjames | Scatter]
I'm not quite sure what that means but the problem that I saw goes a bit like this:

Joe, [26.09.18 15:36]
Start with a brand new virgin scatter and add a mainnet key. Following that add the kylin network manually to scatter. Then add a kylin key (notice that the kylin EOS account isn't found).

Joe, [26.09.18 15:36]
Then attempt to use eostoolkit.io with the EOS mainnet and notice that attempts to attach an EOS mainnet account doesn't work / doesn't cause scatter to request attach.

Joe, [26.09.18 15:37]
The goal is to basically use scatter with the mainnet and testnets simultaneously / easily

Joe, [26.09.18 15:38]
I think it's very close to working but there appears to be something somewhere that is a bit off that prevents it working

Joe, [26.09.18 15:39]
kylin testnet chain Id is correct, check
```

**Comment by jjssoftware** [comment]
I played around further and I believe I've managed to add the Kylin network in the correct / required format. There are a couple of unknowns for me when adding a network manually here.

1. It's not completely clear if the host input text box requires the http / https scheme part or just the FQDN but I suppose ideally it should work fine either way with or without the scheme prefix.
2. I made an assumption that the number value with up / down spinner is a network preference order value. I was only able to get the network added by changing this to the value 1.

I believe that this is the network successfully added:

![screenshot 2018-09-26 20 02 38](https://user-images.githubusercontent.com/536164/46103199-2ac56680-c1c8-11e8-9f48-055a2503a239.png)

Having added the network, attempts to add a valid key for that EOS test network do not work as expected. It would appear that the wrong network is being used by scatter at the point when the key is looked up on-chain or the key isn't recognized for some reason.

The outcome looks like this, refreshing with the top right button doesn't help get the key added:

![screenshot 2018-09-26 20 03 38](https://user-images.githubusercontent.com/536164/46103431-bc34d880-c1c8-11e8-9428-b64ead5fcc87.png)

I do think it's close to working with the network added in this way now because eostoolkit.io does request attach when I change the network on their side to one of the Kylin endpoints; the scatter Login UI successfully presents itself but since there's no valid Kylin key added in scatter, it's not possible to complete the attach / login:

![screenshot 2018-09-26 20 20 43](https://user-images.githubusercontent.com/536164/46103889-df13bc80-c1c9-11e8-8180-d4ab0866fce4.png)

Finally I attempted to get electron app dev tools open to dig a bit deeper but I failed there; I'm not sure if there's a key press handler wired up to enable it to be opened.

**Comment by nsjames** [comment]
Yeah that wouldn't work with extra `http://` or `https://` as those are added from the protocol switcher and would be doubles ( ie `http://http://domain.com` ).

I've added a remover for that now so it can't be done anymore. <3

**Comment by jjssoftware** [comment]
Thanks for this fix, we're moving towards something that will work. For now I've manually removed the `https://` from the domain and now I just have `api-kylin.eosasia.one`

Unfortunately the keys for my kylin account are still not recognized by scatter. I've double checked that my keys are valid, the keys check out fine on bloks, they validate in the greymass key validator and this account is usable in the greymass wallet using the same `api-kylin.eosasia.one` endpoint. 

Have you tested this to verify that it works in v9.0 yourself? It's quick enough:

1. Create a new kylin user with a GET request to this url and you'll get a JSON response containing keys: `http://faucet.cryptokylin.io/create_account?<your_new_account_name>`
2. Add EOS tokens to the new account with a GET request to this url: `http://faucet.cryptokylin.io/get_token?<your_new_account_name>`

**Comment by nsjames** [comment]
Seems to work fine importing it locally

![image](https://user-images.githubusercontent.com/10360675/46129844-83d0e100-c240-11e8-82a4-822a4a6709a6.png)

worked for internal transfer too

![image](https://user-images.githubusercontent.com/10360675/46129912-ad8a0800-c240-11e8-88db-8ae1ed330afd.png)

**Comment by nsjames** [comment]
Though
i'm on the new version. Wait for next release to verify

**Comment by jjssoftware** [comment]
Thanks, ok will do. It would be nice to be able to debug in electron dev tools here. Is there a trick to get that working now in v9.0 ?

**Comment by nsjames** [comment]
Go to Settings. There's a small **</>** icon there.

![image](https://user-images.githubusercontent.com/10360675/46130364-d232af80-c241-11e8-899f-017c0c988800.png)

**Comment by jjssoftware** [comment]
ha yeah just found it ;)

**Comment by jjssoftware** [comment]
ah interesting..I'll retest in v.next but I'm now wondering if this is something special with me / linux / chromium on local.

![screenshot 2018-09-27 08 45 59](https://user-images.githubusercontent.com/536164/46130677-c8a14b80-c231-11e8-9c41-89caed945765.png)

**Comment by jjssoftware** [comment]
Problem found, it's the magic number with the up / down spinner in the Networks view. It describes the http port.

I know that you're going for minimalism in Scatter now but if a user is in the Networks view they're leaning towards advanced mode and this input should probably have a label to describe what it is ;)

**Comment by nsjames** [comment]
Already fixed in next version :P

![image](https://user-images.githubusercontent.com/10360675/46131940-8b46b900-c245-11e8-9569-a791d2735dbd.png)

**Comment by jjssoftware** [comment]
ah good man, onwards and upwards 😉
